#!/bin/awk -f

{
	split($1, path, ":");
	printf "|**";

	printf substr(path[1], 3, length(path[1]));
	printf "**|**";

	printf path[2];
	printf "**|**";

	$1=$2="";
	gsub(/^[ \t]+/, "", $0)
	printf $0;
	print "**|";
}
