#!/bin/awk -f

{
	printf "|**";
	printf substr($1, 3, length($1) - 3)
	printf "**|**";
	printf substr($2, 1, length($2) - 1)
	printf "**|**";
	$1=$2=$3=$4="";
	--NF;
	gsub(/^[ \t]+/, "", $0);
	printf $0;
	print "**|";
}
